### ISSUE TITLE
Make an assumption about a default input

### ISSUE THREAD

**Issue by chrisys** [balena-io-playground/transport#3]
I started up an app with transport, influx and grafana, which couldn't autowire any inputs (because there are none). Should we fall back to enabling something by default? 

![Screenshot 2020-07-24 at 17 27 53](https://user-images.githubusercontent.com/521698/88413415-0e4de180-cdd3-11ea-8a6a-9bcd49bcbd06.png)

**Comment by chrisys** [comment]
The config file looked like this:

![Screenshot 2020-07-24 at 17 33 07](https://user-images.githubusercontent.com/521698/88413813-bf547c00-cdd3-11ea-935f-b0db069aeaa2.png)

**Comment by phil-d-wilson** [comment]
The temperature of the device will be the default input if no inputs are detected (sensor) or enabled by environment variables (e.g. external HTTP).
